# Usa un'immagine base Python
FROM python:3.11-slim

# Imposta variabili d'ambiente
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Installa dipendenze di sistema se necessarie
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Imposta la directory di lavoro nell'immagine
WORKDIR /app_kit

# Copia il file delle dipendenze
COPY requirements_kit.txt requirements_kit.txt

# Installa le dipendenze Python
RUN pip install --no-cache-dir -r requirements_kit.txt

# Copia il resto dell'applicazione nella directory di lavoro
COPY . .

# Crea la directory del database se non esiste
RUN mkdir -p database_kit

# Esponi la porta su cui l'app Flask girerà (Waitress)
EXPOSE 5125

# Comando per avviare l'applicazione quando il container parte
CMD ["python", "app_kit.py"]